from keyboards import coditiion_kb
from keyboards import gender_kb
from keyboards import watches_kb
from keyboards import menu_kb
from keyboards import categories_kb
from keyboards import earrings_kb
from keyboards import braclets_kb
from keyboards import rings_kb
from keyboards import pendants_kb